#!/bin/sh

feh --bg-center /home/hannu/Pictures/Wallpapers/aerial_view_of_new_york_city_tilt_shift_photography-wallpaper-1920x1200.png

unclutter -root -idle 3 &

# Start `dwm` with a modified status bar
while true
do
    DATE=$(date +"%Y-%m-%d %I:%M")
    BAT=$(acpi -b | awk '{ print $4 }' | tr -d ',')
    xsetroot -name "$BAT $DATE"
    sleep 1m
done &
exec dwm


